. "$HOME\.config\alias\express-project-cli\create-new-project.ps1"
. "$HOME\.config\alias\express-project-cli\setup-auth.ps1"
. "$HOME\.config\alias\express-project-cli\setup-database.ps1"
. "$HOME\.config\alias\express-project-cli\setup-mailer.ps1"
. "$HOME\.config\alias\express-project-cli\setup-multer.ps1"